services:
  - type: web
    name: koushik-trading-ai-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_CLIENT_ID
        sync: false
      - key: ANGEL_PIN
        sync: false
      - key: ANGEL_TOTP_SECRET
        sync: false
      - key: ANGEL_PUBLIC_IP
        value: 106.193.147.98
      - key: ANGEL_LOCAL_IP
        value: 192.168.1.1
      - key: ANGEL_MAC_ADDRESS
        value: fe80::216e:6507:4b90:3719
      - key: CORS_ORIGIN
        value: "*"
